# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hejian/work/tsinghua/github/Multiattribute_similarity_join

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hejian/work/tsinghua/github/Multiattribute_similarity_join

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hejian/work/tsinghua/github/Multiattribute_similarity_join/CMakeFiles /Users/hejian/work/tsinghua/github/Multiattribute_similarity_join/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hejian/work/tsinghua/github/Multiattribute_similarity_join/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named similarity_table_search

# Build rule for target.
similarity_table_search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 similarity_table_search
.PHONY : similarity_table_search

# fast build rule for target.
similarity_table_search/fast:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/build
.PHONY : similarity_table_search/fast

#=============================================================================
# Target rules for targets named similarity_table_join

# Build rule for target.
similarity_table_join: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 similarity_table_join
.PHONY : similarity_table_join

# fast build rule for target.
similarity_table_join/fast:
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/build
.PHONY : similarity_table_join/fast

#=============================================================================
# Target rules for targets named gflags_nothreads_static

# Build rule for target.
gflags_nothreads_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gflags_nothreads_static
.PHONY : gflags_nothreads_static

# fast build rule for target.
gflags_nothreads_static/fast:
	$(MAKE) -f lib/gflags/CMakeFiles/gflags_nothreads_static.dir/build.make lib/gflags/CMakeFiles/gflags_nothreads_static.dir/build
.PHONY : gflags_nothreads_static/fast

#=============================================================================
# Target rules for targets named gflags_static

# Build rule for target.
gflags_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gflags_static
.PHONY : gflags_static

# fast build rule for target.
gflags_static/fast:
	$(MAKE) -f lib/gflags/CMakeFiles/gflags_static.dir/build.make lib/gflags/CMakeFiles/gflags_static.dir/build
.PHONY : gflags_static/fast

src/common.o: src/common.cc.o

.PHONY : src/common.o

# target to build an object file
src/common.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/common.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/common.cc.o
.PHONY : src/common.cc.o

src/common.i: src/common.cc.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/common.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/common.cc.i
.PHONY : src/common.cc.i

src/common.s: src/common.cc.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/common.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/common.cc.s
.PHONY : src/common.cc.s

src/core.o: src/core.cc.o

.PHONY : src/core.o

# target to build an object file
src/core.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/core.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/core.cc.o
.PHONY : src/core.cc.o

src/core.i: src/core.cc.i

.PHONY : src/core.i

# target to preprocess a source file
src/core.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/core.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/core.cc.i
.PHONY : src/core.cc.i

src/core.s: src/core.cc.s

.PHONY : src/core.s

# target to generate assembly for a file
src/core.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/core.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/core.cc.s
.PHONY : src/core.cc.s

src/exp/Search0_NoEstimate.o: src/exp/Search0_NoEstimate.cc.o

.PHONY : src/exp/Search0_NoEstimate.o

# target to build an object file
src/exp/Search0_NoEstimate.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search0_NoEstimate.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search0_NoEstimate.cc.o
.PHONY : src/exp/Search0_NoEstimate.cc.o

src/exp/Search0_NoEstimate.i: src/exp/Search0_NoEstimate.cc.i

.PHONY : src/exp/Search0_NoEstimate.i

# target to preprocess a source file
src/exp/Search0_NoEstimate.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search0_NoEstimate.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search0_NoEstimate.cc.i
.PHONY : src/exp/Search0_NoEstimate.cc.i

src/exp/Search0_NoEstimate.s: src/exp/Search0_NoEstimate.cc.s

.PHONY : src/exp/Search0_NoEstimate.s

# target to generate assembly for a file
src/exp/Search0_NoEstimate.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search0_NoEstimate.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search0_NoEstimate.cc.s
.PHONY : src/exp/Search0_NoEstimate.cc.s

src/exp/Search1_Estimate.o: src/exp/Search1_Estimate.cc.o

.PHONY : src/exp/Search1_Estimate.o

# target to build an object file
src/exp/Search1_Estimate.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search1_Estimate.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search1_Estimate.cc.o
.PHONY : src/exp/Search1_Estimate.cc.o

src/exp/Search1_Estimate.i: src/exp/Search1_Estimate.cc.i

.PHONY : src/exp/Search1_Estimate.i

# target to preprocess a source file
src/exp/Search1_Estimate.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search1_Estimate.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search1_Estimate.cc.i
.PHONY : src/exp/Search1_Estimate.cc.i

src/exp/Search1_Estimate.s: src/exp/Search1_Estimate.cc.s

.PHONY : src/exp/Search1_Estimate.s

# target to generate assembly for a file
src/exp/Search1_Estimate.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search1_Estimate.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search1_Estimate.cc.s
.PHONY : src/exp/Search1_Estimate.cc.s

src/exp/Search2_TuneEstimate.o: src/exp/Search2_TuneEstimate.cc.o

.PHONY : src/exp/Search2_TuneEstimate.o

# target to build an object file
src/exp/Search2_TuneEstimate.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search2_TuneEstimate.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search2_TuneEstimate.cc.o
.PHONY : src/exp/Search2_TuneEstimate.cc.o

src/exp/Search2_TuneEstimate.i: src/exp/Search2_TuneEstimate.cc.i

.PHONY : src/exp/Search2_TuneEstimate.i

# target to preprocess a source file
src/exp/Search2_TuneEstimate.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search2_TuneEstimate.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search2_TuneEstimate.cc.i
.PHONY : src/exp/Search2_TuneEstimate.cc.i

src/exp/Search2_TuneEstimate.s: src/exp/Search2_TuneEstimate.cc.s

.PHONY : src/exp/Search2_TuneEstimate.s

# target to generate assembly for a file
src/exp/Search2_TuneEstimate.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/exp/Search2_TuneEstimate.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/exp/Search2_TuneEstimate.cc.s
.PHONY : src/exp/Search2_TuneEstimate.cc.s

src/filter.o: src/filter.cc.o

.PHONY : src/filter.o

# target to build an object file
src/filter.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/filter.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/filter.cc.o
.PHONY : src/filter.cc.o

src/filter.i: src/filter.cc.i

.PHONY : src/filter.i

# target to preprocess a source file
src/filter.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/filter.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/filter.cc.i
.PHONY : src/filter.cc.i

src/filter.s: src/filter.cc.s

.PHONY : src/filter.s

# target to generate assembly for a file
src/filter.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/filter.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/filter.cc.s
.PHONY : src/filter.cc.s

src/lib/debugutils.o: src/lib/debugutils.cpp.o

.PHONY : src/lib/debugutils.o

# target to build an object file
src/lib/debugutils.cpp.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/lib/debugutils.cpp.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/lib/debugutils.cpp.o
.PHONY : src/lib/debugutils.cpp.o

src/lib/debugutils.i: src/lib/debugutils.cpp.i

.PHONY : src/lib/debugutils.i

# target to preprocess a source file
src/lib/debugutils.cpp.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/lib/debugutils.cpp.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/lib/debugutils.cpp.i
.PHONY : src/lib/debugutils.cpp.i

src/lib/debugutils.s: src/lib/debugutils.cpp.s

.PHONY : src/lib/debugutils.s

# target to generate assembly for a file
src/lib/debugutils.cpp.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/lib/debugutils.cpp.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/lib/debugutils.cpp.s
.PHONY : src/lib/debugutils.cpp.s

src/lib/utils.o: src/lib/utils.cpp.o

.PHONY : src/lib/utils.o

# target to build an object file
src/lib/utils.cpp.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/lib/utils.cpp.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/lib/utils.cpp.o
.PHONY : src/lib/utils.cpp.o

src/lib/utils.i: src/lib/utils.cpp.i

.PHONY : src/lib/utils.i

# target to preprocess a source file
src/lib/utils.cpp.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/lib/utils.cpp.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/lib/utils.cpp.i
.PHONY : src/lib/utils.cpp.i

src/lib/utils.s: src/lib/utils.cpp.s

.PHONY : src/lib/utils.s

# target to generate assembly for a file
src/lib/utils.cpp.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/lib/utils.cpp.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/lib/utils.cpp.s
.PHONY : src/lib/utils.cpp.s

src/prefix_index/prefix_index.o: src/prefix_index/prefix_index.cc.o

.PHONY : src/prefix_index/prefix_index.o

# target to build an object file
src/prefix_index/prefix_index.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/prefix_index/prefix_index.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/prefix_index/prefix_index.cc.o
.PHONY : src/prefix_index/prefix_index.cc.o

src/prefix_index/prefix_index.i: src/prefix_index/prefix_index.cc.i

.PHONY : src/prefix_index/prefix_index.i

# target to preprocess a source file
src/prefix_index/prefix_index.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/prefix_index/prefix_index.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/prefix_index/prefix_index.cc.i
.PHONY : src/prefix_index/prefix_index.cc.i

src/prefix_index/prefix_index.s: src/prefix_index/prefix_index.cc.s

.PHONY : src/prefix_index/prefix_index.s

# target to generate assembly for a file
src/prefix_index/prefix_index.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/prefix_index/prefix_index.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/prefix_index/prefix_index.cc.s
.PHONY : src/prefix_index/prefix_index.cc.s

src/sim_table.o: src/sim_table.cc.o

.PHONY : src/sim_table.o

# target to build an object file
src/sim_table.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/sim_table.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/sim_table.cc.o
.PHONY : src/sim_table.cc.o

src/sim_table.i: src/sim_table.cc.i

.PHONY : src/sim_table.i

# target to preprocess a source file
src/sim_table.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/sim_table.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/sim_table.cc.i
.PHONY : src/sim_table.cc.i

src/sim_table.s: src/sim_table.cc.s

.PHONY : src/sim_table.s

# target to generate assembly for a file
src/sim_table.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/sim_table.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/sim_table.cc.s
.PHONY : src/sim_table.cc.s

src/test/help_text.o: src/test/help_text.cc.o

.PHONY : src/test/help_text.o

# target to build an object file
src/test/help_text.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/test/help_text.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/test/help_text.cc.o
.PHONY : src/test/help_text.cc.o

src/test/help_text.i: src/test/help_text.cc.i

.PHONY : src/test/help_text.i

# target to preprocess a source file
src/test/help_text.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/test/help_text.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/test/help_text.cc.i
.PHONY : src/test/help_text.cc.i

src/test/help_text.s: src/test/help_text.cc.s

.PHONY : src/test/help_text.s

# target to generate assembly for a file
src/test/help_text.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/test/help_text.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/test/help_text.cc.s
.PHONY : src/test/help_text.cc.s

src/test/sim_table_join.o: src/test/sim_table_join.cc.o

.PHONY : src/test/sim_table_join.o

# target to build an object file
src/test/sim_table_join.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/test/sim_table_join.cc.o
.PHONY : src/test/sim_table_join.cc.o

src/test/sim_table_join.i: src/test/sim_table_join.cc.i

.PHONY : src/test/sim_table_join.i

# target to preprocess a source file
src/test/sim_table_join.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/test/sim_table_join.cc.i
.PHONY : src/test/sim_table_join.cc.i

src/test/sim_table_join.s: src/test/sim_table_join.cc.s

.PHONY : src/test/sim_table_join.s

# target to generate assembly for a file
src/test/sim_table_join.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/test/sim_table_join.cc.s
.PHONY : src/test/sim_table_join.cc.s

src/test/sim_table_search.o: src/test/sim_table_search.cc.o

.PHONY : src/test/sim_table_search.o

# target to build an object file
src/test/sim_table_search.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/test/sim_table_search.cc.o
.PHONY : src/test/sim_table_search.cc.o

src/test/sim_table_search.i: src/test/sim_table_search.cc.i

.PHONY : src/test/sim_table_search.i

# target to preprocess a source file
src/test/sim_table_search.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/test/sim_table_search.cc.i
.PHONY : src/test/sim_table_search.cc.i

src/test/sim_table_search.s: src/test/sim_table_search.cc.s

.PHONY : src/test/sim_table_search.s

# target to generate assembly for a file
src/test/sim_table_search.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/test/sim_table_search.cc.s
.PHONY : src/test/sim_table_search.cc.s

src/tree_index/desicion_tree_index.o: src/tree_index/desicion_tree_index.cc.o

.PHONY : src/tree_index/desicion_tree_index.o

# target to build an object file
src/tree_index/desicion_tree_index.cc.o:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/tree_index/desicion_tree_index.cc.o
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/tree_index/desicion_tree_index.cc.o
.PHONY : src/tree_index/desicion_tree_index.cc.o

src/tree_index/desicion_tree_index.i: src/tree_index/desicion_tree_index.cc.i

.PHONY : src/tree_index/desicion_tree_index.i

# target to preprocess a source file
src/tree_index/desicion_tree_index.cc.i:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/tree_index/desicion_tree_index.cc.i
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/tree_index/desicion_tree_index.cc.i
.PHONY : src/tree_index/desicion_tree_index.cc.i

src/tree_index/desicion_tree_index.s: src/tree_index/desicion_tree_index.cc.s

.PHONY : src/tree_index/desicion_tree_index.s

# target to generate assembly for a file
src/tree_index/desicion_tree_index.cc.s:
	$(MAKE) -f CMakeFiles/similarity_table_search.dir/build.make CMakeFiles/similarity_table_search.dir/src/tree_index/desicion_tree_index.cc.s
	$(MAKE) -f CMakeFiles/similarity_table_join.dir/build.make CMakeFiles/similarity_table_join.dir/src/tree_index/desicion_tree_index.cc.s
.PHONY : src/tree_index/desicion_tree_index.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... install/strip"
	@echo "... similarity_table_search"
	@echo "... similarity_table_join"
	@echo "... gflags_nothreads_static"
	@echo "... gflags_static"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/exp/Search0_NoEstimate.o"
	@echo "... src/exp/Search0_NoEstimate.i"
	@echo "... src/exp/Search0_NoEstimate.s"
	@echo "... src/exp/Search1_Estimate.o"
	@echo "... src/exp/Search1_Estimate.i"
	@echo "... src/exp/Search1_Estimate.s"
	@echo "... src/exp/Search2_TuneEstimate.o"
	@echo "... src/exp/Search2_TuneEstimate.i"
	@echo "... src/exp/Search2_TuneEstimate.s"
	@echo "... src/filter.o"
	@echo "... src/filter.i"
	@echo "... src/filter.s"
	@echo "... src/lib/debugutils.o"
	@echo "... src/lib/debugutils.i"
	@echo "... src/lib/debugutils.s"
	@echo "... src/lib/utils.o"
	@echo "... src/lib/utils.i"
	@echo "... src/lib/utils.s"
	@echo "... src/prefix_index/prefix_index.o"
	@echo "... src/prefix_index/prefix_index.i"
	@echo "... src/prefix_index/prefix_index.s"
	@echo "... src/sim_table.o"
	@echo "... src/sim_table.i"
	@echo "... src/sim_table.s"
	@echo "... src/test/help_text.o"
	@echo "... src/test/help_text.i"
	@echo "... src/test/help_text.s"
	@echo "... src/test/sim_table_join.o"
	@echo "... src/test/sim_table_join.i"
	@echo "... src/test/sim_table_join.s"
	@echo "... src/test/sim_table_search.o"
	@echo "... src/test/sim_table_search.i"
	@echo "... src/test/sim_table_search.s"
	@echo "... src/tree_index/desicion_tree_index.o"
	@echo "... src/tree_index/desicion_tree_index.i"
	@echo "... src/tree_index/desicion_tree_index.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

